[build]
  command = "npm install && npm run build"
  functions = "functions"

[build.environment]
  NODE_ENV="--openssl-legacy-provider"
  CI="false"

[[redirects]]
  from="/stripe/*"
  to="/.netlify/functions/server/stripe/:splat"
