[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/web/*"
  to = "/.netlify/functions/web/stripe/:splat"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from="/stripe/*"
  to = "/.netlify/functions/api/stripe/:splat"

[[redirects]]
  from="/"
  to="/.netlify/functions/api/"
